# Generated by Django 5.1.6 on 2025-03-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_item_description_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
